; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-BG02BVD5

lib_deps =
    olikraus/U8g2
    rfetick/MPU6050_light
    pololu/VL6180X

build_cxx_flags = -fno-exceptions -fno-rtti
build_flags = -Os -Wall -Wextra
build_src_flags = -Os -Wall -Werror -Wextra

build_src_filter = +<*> -<main_test.cpp>